name: Publish changes from master to gh-pages

on:
    push:
        branches:
            - master

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              name: Checkout
              with:
                  path: build-clone
                  submodules: true
                  fetch-depth: 0
            - uses: actions/checkout@v2
              name: Checkout dist
              with:
                  ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  path: dist-clone
                  ref: do-dist
                  submodules: true

            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"

            - name: Get yarn cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              working-directory: ./build-clone
              run: yarn install
            - name: Build app
              working-directory: ./build-clone
              run: yarn build

            - name: Copy to dist checkout
              working-directory: ./dist-clone
              run: |
                # Get a clean set up
                git rm -rf . || true
                git clean -fxd
                git reset

                cp -r $GITHUB_WORKSPACE/build-clone/dist/. .

            - name: Push to dist branch
              working-directory: ./dist-clone
              run: |
                ls -al

                git add --all

                git config user.name $GITHUB_ACTOR
                git config user.email $GITHUB_ACTOR@users.noreply.github.com

                git commit -m "Update distribution"

                git push origin
